### ISSUE TITLE
CRC Generation

### ISSUE THREAD

**Issue by derekm** [automategreen/hub-i#2]
The CRC byte is a "7-bit linear-feedback shift register with taps at the two most-significant bits" as documented here:

http://cache.insteon.com/pdf/insteondetails.pdf

http://cache.insteon.com/developer/developer-guide-022009-en.pdf

**Comment by derekm** [comment]
Not sure if this is close, but here's my first attempt at implementing a "7-bit linear-feedback shift register with taps at the two most-significant bits" in Python...

```
import sys

input = "hello, world"

crc = 0
for byte in input:
  byte = ord(byte)
  cyc = byte ^ crc
  for i in range(7):
    bit8 = cyc >> 7
    bit7 = cyc >> 6 & 0b10
    new_bit1 = bit8 ^ bit7
    crc = cyc << 1 & (sys.maxint&255) | new_bit1
  print "step {0}: {1:b}".format(chr(byte), crc)

print "{0:b}".format(crc)
```

The sys.maxint&255 nonsense on the last line of the inner loop is because Python doesn't have a 8-char datatype as far as I can tell, so nothing was falling off during the left-shifts.

**Comment by brandongoode** [comment]
Just pushed the coded with the working CRC
